apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmf622-compares
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  #storageClassName: managed-nfs-storage 
  accessModes:
    - ReadWriteOnce
