kind: Deployment
apiVersion: apps/v1
metadata:
  name: tmf622
  labels:
    app: tmf622
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmf622
  template:
    metadata:
      labels:
        app: tmf622
    spec:
      containers:
      - name: tmf622
        image: >-
          image-registry.openshift-image-registry.svc:5000/robert0714-lee-dev/tmf622:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: compares-data
          mountPath: /app/comparelogs
        env:
        - name: MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: tmf622
              resource: requests.memory
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: tmf622
              resource: limits.memory
        resources:
          requests: 
            memory: 1G
          limits: 
            memory: 1.5Gi  
      volumes:
      - name: compares-data
        persistentVolumeClaim:
          claimName: tmf622-compares
      

