apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: oracle-persistent
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: orcl
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  status: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: oracle19c
    name: oracle19c
  spec:
    replicas: 1
    selector:
      app: oracle19c
      deploymentconfig: oracle19c
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: oracle19c
          deploymentconfig: oracle19c
      spec:
        containers:
        - name: oracle19c
          imagePullPolicy: Always
          ports:
          - containerPort: 1521
            protocol: TCP
          - containerPort: 5500
            protocol: TCP
          resources:
            limits:
              memory: 10Gi
            requests:
              memory: 3Gi
          securityContext: {}
          env:
            - name: TZ
              value: 'Asia/Taipei'
            - name: ORACLE_ALLOW_REMOTE
              value: 'true'
            - name: ORACLE_CHARACTERSET
              value: AL32UTF8
            - name: ORACLE_ENABLE_XDB
              value: 'true'
            - name: ORACLE_PDB
              value: orcl
            - name: ORACLE_PWD
              value: oracle
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /ORCL
            name: orcl
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 54321
        serviceAccount: oracle
        serviceAccountName: oracle
        terminationGracePeriodSeconds: 30
        volumes:
        - name: orcl
          persistentVolumeClaim:
            claimName: orcl
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - oracle19c
        from:
          kind: ImageStreamTag
          name: oracle-database:19.3.0-ee
      type: ImageChange
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: oracle19c
    name: oracle19c
  spec:
    ports:
    - name: 1521-tcp
      port: 1521
      protocol: TCP
      targetPort: 1521
    - name: 5500-tcp
      port: 5500
      protocol: TCP
      targetPort: 5500
    selector:
      deploymentconfig: oracle19c
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}