apiVersion: v1
kind: Service
metadata:
  labels:
    app: h2
    service: h2  
  name: h2
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: h2
  sessionAffinity: None
  type: ClusterIP
