apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnidbdata
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  #storageClassName: managed-nfs-storage 
  accessModes:
    - ReadWriteOnce
