apiVersion: v1
kind: Service
metadata:
  labels:
    app: omnidb
    service: omnidb  
  name: omnidb
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: omnidb
  sessionAffinity: None
  type: ClusterIP
